project:
  type: website

website:
  title: "Random blog"
  site-url: https://lbm364dl.github.io/blog
  description: "Random blog with random topics"
  repo-url: https://github.com/lbm364dl/blog
  repo-actions: [edit, issue]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lbm364dl
      - icon: linkedin
        href: https://www.linkedin.com/in/catalin-sorin-covaci-a6bb44248/
      - icon: envelope
        href: mailto:ctl.covaci@gmail.com
      - icon: rss
        href: index.xml
  page-footer:
    right: |
      This blog was built with <a href="https://quarto.org/">Quarto</a>.
  google-analytics: "G-27FX5XLDN9"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    include-after-body: include-after.html

execute:
  freeze: true
